### ISSUE TITLE
Feat Request : Add an icon to the app to identify easily

### ISSUE THREAD

**Issue by BedBug2479** [AbdurazaaqMohammed/AntiSplit-M#10]
TITLE

**Comment by AbdurazaaqMohammed** [comment]
![AntiSplit M](https://github.com/user-attachments/assets/99a3cd88-4a7f-48c6-87a2-a424c3c5d9ba)

This is the best I could come up with, if anyone has better ideas or makes one I am happy to figure out something better

**Comment by BedBug2479** [comment]
> This is the best I could come up with, if anyone has better ideas or makes one I am happy to figure out something better

As long as i can identify this app in the All Apps screen, it is fine

**Comment by Vertuhai** [comment]
> ![AntiSplit M](https://private-user-images.githubusercontent.com/56937889/355629353-99a3cd88-4a7f-48c6-87a2-a424c3c5d9ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTIxNzQsIm5iZiI6MTcyMzA5MTg3NCwicGF0aCI6Ii81NjkzNzg4OS8zNTU2MjkzNTMtOTlhM2NkODgtNGE3Zi00OGM2LTg3YTItYTQyNGMzYzVkOWJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA0Mzc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5MjJlODI2NDNmNGRlZDNjYzgwYTgyMTgwZDkzODAyZmRmNWUwYTg0MjExYzhhYzQ0YzQwMmU2OTExOTY4NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._oF84Qehio5s8QfZbmzYtJOetAI-gVL3aT2oMWkCOmo)
> 
> This is the best I could come up with, if anyone has better ideas or makes one I am happy to figure out something better

Great icon !
