### ISSUE TITLE
Broken searchbar with amoled theme

### ISSUE THREAD

**Issue by 0xrxL** [AbdurazaaqMohammed/AntiSplit-M#100]
![367585699-1f9ddbf3-0067-425b-b8ca-d92fee57a211](https://github.com/user-attachments/assets/0adce446-38ac-4584-ba6b-9615a83107b9)

**Comment by 0xrxL** [comment]
Also both sorting and clear buttons should be aligned.

**Comment by AbdurazaaqMohammed** [comment]
I update the [latest release](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/latest), I put a custom clear button for black theme only, it is aligned in all themes

![WhatsApp Image 2024-10-01 at 16 16 03_8ff84af9](https://github.com/user-attachments/assets/28083431-7c6b-498f-b494-c19b8454ade1)

**Comment by 0xrxL** [comment]
@AbdurazaaqMohammed Why not for all themes. Should be a better approach imho.

**Comment by drogga** [comment]
Probably because that custom one is always there, even if there's nothing in the input field...
