### ISSUE TITLE
Apply black theme searchbar buttons in every theme

### ISSUE THREAD

**Issue by 0xrxL** [AbdurazaaqMohammed/AntiSplit-M#101]
For a consistency design

![372637326-28083431-7c6b-498f-b494-c19b8454ade1](https://github.com/user-attachments/assets/0c325b9c-0e6a-4655-abf4-4bd6e18defc1)

**Comment by Kuddus73** [comment]
I don't know about this suggestion, because the custom `Clear` button is always there even when the input field is empty.

**Comment by 0xrxL** [comment]
> I don't know about this suggestion, because the custom `Clear` button is always there even when the input field is empty.

Select a different theme, and clear button will be integrated inside the searchbar. 👍

**Comment by Kuddus73** [comment]
> Select a different theme, and clear button will be integrated inside the searchbar. 👍

Of course, that's how it currently works.
But if your suggestion is implemented, it won't anymore.

**Comment by AbdurazaaqMohammed** [comment]
https://github.com/user-attachments/assets/93d83311-e3c8-49f4-9642-8107baca1efa

In the [latest release](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/latest), I put the 2 buttons inside the search bar in all themes, and clear button not there when empty
