### ISSUE TITLE
Dynamic icon for monet theme

### ISSUE THREAD

**Issue by 0xrxL** [AbdurazaaqMohammed/AntiSplit-M#102]
![20241002_205032](https://github.com/user-attachments/assets/0cbc4150-4cbb-4b88-9352-3fbc6bd7042a)

And (if you need it) this is a tutorial about how to implement it: https://siddroid.com/post/android/supporting-adaptive-themed-icons-on-android-13/#monochrome-icon

**Comment by AbdurazaaqMohammed** [comment]
I tried to add it. It is not supported on my device so I am not sure if I did it correctly

**Comment by 0xrxL** [comment]
> I tried to add it. It is not supported on my device so I am not sure if I did it correctly

Should be less zoomed with a white background (like before):

![Screenshot_20241007_074031_One UI Home](https://github.com/user-attachments/assets/6057a572-3364-4d82-85b4-74fb628c8216)

and seems the icon I posted above is not good for dynamic palette feature

![Screenshot_20241007_074856_One UI Home](https://github.com/user-attachments/assets/4f6feb8b-54d5-4c20-aafd-bc8778132526)

**Comment by 0xrxL** [comment]
This is a better monet icon, try to implement this instead 👍 

![monet](https://github.com/user-attachments/assets/4a3d9eba-2c9f-45c0-9c70-73010c02b690)

**Comment by AbdurazaaqMohammed** [comment]
Try

https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/download/2.1.0/AntiSplit-M.v2.1.0.apk

**Comment by 0xrxL** [comment]
> Try
> 
> https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/download/2.1.0/AntiSplit-M.v2.1.0.apk

Almost fixed... It's still a bit not centered, and background is still black.

![Screenshot_20241007_194422_One UI Home](https://github.com/user-attachments/assets/2249c4b9-811f-4158-959d-7881030afa66)
![Screenshot_20241007_194333_One UI Home](https://github.com/user-attachments/assets/ec9d5db9-0171-49b3-8707-bdf8d9b6ecf3)

**Comment by AbdurazaaqMohammed** [comment]
It should be centered and white background now

https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/download/2.1.0/AntiSplit-M.v2.1.0.apk

**Comment by 0xrxL** [comment]
> It should be centered and white background now
> 
> https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/download/2.1.0/AntiSplit-M.v2.1.0.apk

Thanks, it's fixed now.

![Screenshot_20241007_204020_One UI Home](https://github.com/user-attachments/assets/850dd3d0-7a28-4971-b451-bf785a5924aa)
![Screenshot_20241007_203946_One UI Home](https://github.com/user-attachments/assets/a1f19d42-1779-4b80-b4c4-4cbd643aead5)


I'll send you another monet icon, to fix also APK word that is currently invisible. 👍

**Comment by drogga** [comment]
I'm pretty sure the adaptive (aka. dynamic/round/monet/monochrome) need to be as .xml (vector), rather than .png or .svg, please keep that in mind and maybe try https://chatgpt.com/g/g-3XuOZBj67-monochrome-icon-generator they claim to generate _good_ monochrome icons or at least convert them to (if you haven't used it, I haven't).

**Comment by 0xrxL** [comment]
It's already .xml in the app source code, but maybe Android wants some parts to be black instead of transparent to be able to view them correctly. Try this...

![374084308-4a3d9eba-2c9f-45c0-9c70-73010c02b690](https://github.com/user-attachments/assets/4a133f9f-6c5f-45c2-972a-d874d270e7a2)

**Comment by drogga** [comment]
I was referring to the dev's comment in ticket 104:

> The adapative icon need svg to work, I had to convert the png to SVG, I changed it again, it should look more or less same now

**Comment by 0xrxL** [comment]
> I was referring to the dev's comment in ticket 104:
> 
> > The adapative icon need svg to work, I had to convert the png to SVG, I changed it again, it should look more or less same now

I tried to convert it to SVG, but once I added to an empty AS project to check the result, its size didn't was right. 🤷‍♂️

**Comment by AbdurazaaqMohammed** [comment]
I change it again, it should be good now 
![image](https://github.com/user-attachments/assets/be0ff490-2fd6-4f18-a5b8-0463a0cad8bd)

**Comment by 0xrxL** [comment]
> I change it again, it should be good now ![image](https://private-user-images.githubusercontent.com/56937889/374333176-be0ff490-2fd6-4f18-a5b8-0463a0cad8bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzMzk2OTQsIm5iZiI6MTcyODMzOTM5NCwicGF0aCI6Ii81NjkzNzg4OS8zNzQzMzMxNzYtYmUwZmY0OTAtMmZkNi00ZjE4LWE1YjgtMDQ2M2EwY2FkOGJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDIyMTYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhMjRlZDQxM2IzZTM5ZTk5ZDZmZTQxMWM1ZWI5NmUxZjZlY2FiZWZmNmNhNDIyNjA1NjkzYTM2MzRjY2ZmN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qPUjHIy9HNLjZpg7qctEcOOR5tapUpgF3oe2E691SSc)

Thanks! Hope it will looks in the same way on Android too.

**Comment by 0xrxL** [comment]
@AbdurazaaqMohammed I removed the weird shadow around the normal icon, that also appears on the launcher.

![365320142-508c3b10-2d12-4511-960b-f155c93a9127](https://github.com/user-attachments/assets/46e4f82e-6681-43ef-8c86-f82ec37b290f)

**Comment by drogga** [comment]
Looking at it in full size (4096x4096) I can see semi-vertical lines in the red patch sticker - can you remove them and align it perfectly, because it's tilted a bit to the left currently and maybe make the white separation indicator (jagged line) at the both ends sharp instead of rounded and where is rounded make it sharp, or at least rounded edges everywhere to make it more visually appealing and consistent ? [~6 edits]

**Comment by 0xrxL** [comment]
I will consider these suggestions.

P.S: The semi-vertical lines are intended to create the patch effect, however.

**Comment by drogga** [comment]
> P.S: The semi-vertical lines are intended to create the patch effect, however.

Oh I don't mean the black ones, but rendering artifacts that are only visible when looking at the patch in original/full size, otherwise aren't (they look like - - - and are easily noticeable in a browser on PC and if you really zoom in to max on Android).

**Comment by 0xrxL** [comment]
Yes, I understood that. And yes, the effect of those white lines is wool-like blanket (though they're actually too small to see).

**Comment by AbdurazaaqMohammed** [comment]
I thought I had removed the shadow from xml already but I had only done it in the monochrome icon. In the [latest release](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/latest), I have removed it fully
