### ISSUE TITLE
Icon bugs

### ISSUE THREAD

**Issue by Kuddus73** [AbdurazaaqMohammed/AntiSplit-M#104]
This is how the icon appears on v2.0.9:
![ _20241007_101716](https://github.com/user-attachments/assets/7542dd72-ff31-4260-ad45-69ef200a7c72)

v.2.1.0 has this bugs:
1. Background is not transparent
2. Icon's body is distorted
3. Icon's picture is not full, it's cut off
![ _20241007_101456](https://github.com/user-attachments/assets/1b9b7297-8096-4487-9300-b197639e7d27)

**Comment by 0xrxL** [comment]
@Kuddus73 https://github.com/AbdurazaaqMohammed/AntiSplit-M/issues/102

I updated this thread with some feedbacks and a fix. Follow this to prevents the opening of more issues.

**Comment by AbdurazaaqMohammed** [comment]
It inside now

check https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/download/2.1.0/AntiSplit-M.v2.1.0.apk

**Comment by Kuddus73** [comment]
> It inside now

@AbdurazaaqMohammed why is it inside and not like how it was on v2.0.9?
v2.0.9 version looked more visually pleasant.

**Comment by AbdurazaaqMohammed** [comment]
The adapative icon need svg to work, I had to convert the png to SVG, I changed it again, it should look more or less same now
