### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by NitishKartik** [AbdurazaaqMohammed/AntiSplit-M#109]
java.io.FileNotFoundException: No '*.apk' files in directory: /data/user/0/com.abdurazaaqmohammed.AntiSplit/cachecom.reandroid.apk.ApkBundle.loadApkDirectory(SourceFile:379)com.reandroid.apkeditor.merge.Merger.extractAndLoad(SourceFile:332)com.reandroid.apkeditor.merge.Merger.run(SourceFile:78)com.abdurazaaqmohammed.AntiSplit.main.MainActivity$ProcessTask.doInBackground(SourceFile:41)com.abdurazaaqmohammed.AntiSplit.main.MainActivity$ProcessTask.doInBackground(SourceFile:1)android.os.AsyncTask$3.call(AsyncTask.java:394)java.util.concurrent.FutureTask.run(FutureTask.java:266)android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)java.lang.Thread.run(Thread.java:923)Searching apk files…/document/primary:MT2/apks/SS Decrypted_1.apkSkipping AndroidManifest.xml: Not an APK fileSkipping res/drawable-mdpi-v4/ic_site_settings.png: Not an APK fileSkipping res/drawable-mdpi-v4/notification_badge.png: Not an APK fileSkipping res/drawable-hdpi-v4/ic_site_settings.png: Not an APK fileSkipping res/drawable-hdpi-v4/last_resort_runtime_host_logo.png: Not an APK fileSkipping res/drawable-hdpi-v4/notification_badge.png: Not an APK fileSkipping res/drawable-xhdpi-v4/ic_site_settings.png: Not an APK fileSkipping res/drawable-xhdpi-v4/notification_badge.png: Not an APK fileSkipping res/drawable-xhdpi-v4/splash_icon.xml: Not an APK fileSkipping res/drawable-xxhdpi-v4/ic_site_settings.png: Not an APK fileSkipping res/drawable-xxhdpi-v4/notification_badge.png: Not an APK fileSkipping res/drawable-xxxhdpi-v4/ic_site_settings.png: Not an APK fileSkipping res/drawable-xxxhdpi-v4/notification_badge.png: Not an APK fileSkipping res/drawable-xxxhdpi-v4/splash_icon.xml: Not an APK fileSkipping res/layout/choose_host_browser_dialog.xml: Not an APK fileSkipping res/layout/host_browser_list_item.xml: Not an APK fileSkipping res/layout/webapp_splash_screen_large.xml: Not an APK fileSkipping res/layout/webapp_splash_screen_no_icon.xml: Not an APK fileSkipping res/layout-v31/splash_screen_view.xml: Not an APK fileSkipping res/mipmap-mdpi-v4/maskable_app_icon.xml: Not an APK fileSkipping res/mipmap-xxxhdpi-v4/app_icon.xml: Not an APK fileSkipping res/mipmap-xxxhdpi-v4/ic_launcher.xml: Not an APK fileSkipping res/mipmap-nodpi-v4/app_icon_xxxhdpi.png: Not an APK fileSkipping res/mipmap-nodpi-v4/splash_icon_xxxhdpi.png: Not an APK fileSkipping res/xml/shortcuts.xml: Not an APK fileSkipping resources.arsc: Not an APK fileSkipping classes.dex: Not an APK fileSkipping META-INF/APP.SF: Not an APK fileSkipping META-INF/APP.RSA: Not an APK fileSkipping META-INF/BROWSER.SF: Not an APK fileSkipping META-INF/BROWSER.RSA: Not an APK fileSkipping META-INF/MANIFEST.MF: Not an APK fileSkipping AndroidManifest.xml: Not an APK fileSkipping res/drawable-mdpi-v4/ic_site_settings.png: Not an APK fileSkipping res/drawable-mdpi-v4/notification_badge.png: Not an APK fileSkipping res/drawable-hdpi-v4/ic_site_settings.png: Not an APK fileSkipping res/drawable-hdpi-v4/last_resort_runtime_host_logo.png: Not an APK file

**Comment by AbdurazaaqMohammed** [comment]
> SS Decrypted_1.apk

You are trying to merge a single regular APK. This app is for merging several splits (base.apk, config.armeabi_v7a.apk, config.xxhdpi.apk etc.) or split APKs (APKS/XAPK/APKM, just archives containing the former).
