### ISSUE TITLE
Crash Report 

### ISSUE THREAD

**Issue by kozmo2k4** [AbdurazaaqMohammed/AntiSplit-M#111]
App trying to split: twitter.android_10.64.2-release.0.apkm downloaded from Apkmirror
Device: Nexus 7 (2013)
OS: crDroid 7.46, Android 11

Error message:
java.io.IOException: Error on ZipFile /data/user/0/com.abdurazaaqmohammed.AntiSplit/cache/twitter.android_10.64.2-release.0_antisplit.apkorg.apache.commons.compress.archivers.zip.ZipFile.<init>(SourceFile:39)org.apache.commons.compress.archivers.zip.ZipFile.<init>(SourceFile:12)org.apache.commons.compress.archivers.zip.ZipFile.<init>(SourceFile:9)org.apache.commons.compress.archivers.zip.ZipFile.<init>(SourceFile:2)org.apache.commons.compress.archivers.zip.ZipFile.<init>(SourceFile:1)com.reandroid.apkeditor.merge.Merger.extractAndLoad(SourceFile:317)com.reandroid.apkeditor.merge.Merger.run(SourceFile:78)com.abdurazaaqmohammed.AntiSplit.main.MainActivity$ProcessTask.doInBackground(SourceFile:41)com.abdurazaaqmohammed.AntiSplit.main.MainActivity$ProcessTask.doInBackground(SourceFile:1)android.os.AsyncTask$3.call(AsyncTask.java:394)java.util.concurrent.FutureTask.run(FutureTask.java:266)android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)java.lang.Thread.run(Thread.java:923)

**Comment by AbdurazaaqMohammed** [comment]
I could not replicate it on Android 11 emulator.

> java.io.IOException: Error on ZipFile /data/user/0/com.abdurazaaqmohammed.AntiSplit/cache/twitter.android_10.64.2-release.0_**antisplit**.apk

This file should not be in the cache directory at all. Is it possible that you did select this file (twitter.android_10.64.2-release.0_antisplit.apk), previously created by AntiSplit-M (which possibly failed for a different reason) instead of the apkm file?

**Comment by kozmo2k4** [comment]
Updated the app to v2.1.1, and was able to split the twitter.android_10.64.2-release.0.apkm successfully. 
This time the whole process seemed much faster, than in previous versions of the app.
Thanks
