### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shifoc** [AbdurazaaqMohammed/AntiSplit-M#115]
java.lang.NullPointerExceptionjava.io.File.<init>(File.java:283)
com.abdurazaaqmohammed.AntiSplit.main.DeviceSpecsUtil.getListOfSplits(SourceFile:65)
com.abdurazaaqmohammed.AntiSplit.main.MainActivity$ProcessTask.doInBackground(SourceFile:9)
com.abdurazaaqmohammed.AntiSplit.main.MainActivity$ProcessTask.doInBackground(SourceFile:1)
android.os.AsyncTask$3.call(AsyncTask.java:394)
java.util.concurrent.FutureTask.run(FutureTask.java:264)
android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
java.lang.Thread.run(Thread.java:1012)

SDK 34
AntiSplit M 2.1.3
Storage permission granted: true
Output directory: /storage/emulated/0/AntiSplit-M/AntiSplit-M.v2.1.3.apk

**Comment by shifoc** [comment]
Android 14,
https://www.apkmirror.com/apk/redditinc/reddit/reddit-2024-49-0-release/reddit-2024-49-0-3-android-apk-download/

**Comment by drogga** [comment]
@AbdurazaaqMohammed

**Comment by AbdurazaaqMohammed** [comment]
> Output directory: /storage/emulated/0/AntiSplit-M/**AntiSplit-M.v2.1.3.apk**

Are you sure you selected the correct file? It looks like you may have selected the APK of AntiSplit M itself by accident.

**Comment by shifoc** [comment]
You might be right, so I will close the issue for now
