### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by feralfenrir** [AbdurazaaqMohammed/AntiSplit-M#116]
java.io.IOException: Trying to rewind 4 but buffer only has 3com.j256.simplezip.RewindableInputStream.rewind(SourceFile:41)com.j256.simplezip.format.ZipFileHeader.read(SourceFile:12)com.j256.simplezip.ZipFileInput.readFileHeader(SourceFile:13)com.abdurazaaqmohammed.AntiSplit.main.DeviceSpecsUtil.getListOfSplits(SourceFile:17)com.abdurazaaqmohammed.AntiSplit.main.MainActivity.showApkSelectionDialog(SourceFile:5)com.abdurazaaqmohammed.AntiSplit.main.MainActivity.processOneSplitApkUri(SourceFile:7)com.abdurazaaqmohammed.AntiSplit.main.MainActivity.onActivityResult(SourceFile:44)android.app.Activity.onActivityResult(Activity.java:7511)android.app.Activity.internalDispatchActivityResult(Activity.java:9396)android.app.Activity.dispatchActivityResult(Activity.java:9373)android.app.ActivityThread.deliverResults(ActivityThread.java:5948)android.app.ActivityThread.handleSendResult(ActivityThread.java:5998)android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:78)android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:63)android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:133)android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:103)android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:80)android.app.ActivityThread$H.handleMessage(ActivityThread.java:2719)android.os.Handler.dispatchMessage(Handler.java:109)android.os.Looper.loopOnce(Looper.java:232)android.os.Looper.loop(Looper.java:317)android.app.ActivityThread.main(ActivityThread.java:8787)java.lang.reflect.Method.invoke(Native Method)com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)com.android.internal.os.ZygoteInit.main(ZygoteInit.java:871)SDK 35AntiSplit M 2.1.3Storage permission granted: true

**Comment by feralfenrir** [comment]
I got a crash with the latest beta build for X(Twitter) v10.72.0 beta

**Comment by AbdurazaaqMohammed** [comment]
Fixed in [latest release](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/latest)
