### ISSUE TITLE
APK file signature!

### ISSUE THREAD

**Issue by Vertuhai** [AbdurazaaqMohammed/AntiSplit-M#12]
The program signs the package only for older Android devices - V1.
This is why many people are faced with problems on Android 14, various types of errors.
If possible, then you need to implement a signature in the program - V1; V2; V3.

**Comment by AbdurazaaqMohammed** [comment]
Done in [1.6.3.6](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/tag/1.6.3.6)
