### ISSUE TITLE
Cannot press "Select split APK to Merge" in vertical orientation

### ISSUE THREAD

**Issue by fino963** [AbdurazaaqMohammed/AntiSplit-M#21]
On Pixel 6 (and assuming 7 & 8)- unable to select the topmost menu option while in vertical orientation in app.

The _Select split APK to Merge/Split_ option is located under the front facing camera on the device which does not allow selection.

Workaround is to change to landscape/horizontal orientation.

![Screenshot_20240817-084113](https://github.com/user-attachments/assets/477d13dd-868a-4239-b265-fe527e451066)

**Comment by AbdurazaaqMohammed** [comment]
Ok, I added the app bar which will serve as padding, it should be fine now

![WhatsApp Image 2024-08-17 at 15 44 39_5e4b4c58](https://github.com/user-attachments/assets/f07bc3f5-b5a6-45b6-81e1-357096cf39f6)

**Comment by fino963** [comment]
Maybe Pixels are behaving differently. The topmost option disappeared!

![Screenshot_20240817-145929](https://github.com/user-attachments/assets/f3f82d33-da7b-4e74-9fe0-bc9eecce85cd)

![Screenshot_20240817-145939](https://github.com/user-attachments/assets/c6328102-bd8b-423c-8558-86b1e1c33082)

**Comment by AbdurazaaqMohammed** [comment]
Bruh

Okay I just added a bunch of padding now it should be fine

![WhatsApp Image 2024-08-17 at 16 11 33_443d37d8](https://github.com/user-attachments/assets/583f4b59-f04c-453a-bfc1-971ec41fe18c)

**Comment by AbdurazaaqMohammed** [comment]
> Just to clarify, and I know this is a bit off-topic, is the goal of the project to keep the app simple in both size and design?

Yes, I don't see the need to have a fancy UI for a simple app like this, also I want to maintain compatibility with older Android versions

And I will try making a settings menu
