### ISSUE TITLE
Visual issues

### ISSUE THREAD

**Issue by teddysulaimanGL** [AbdurazaaqMohammed/AntiSplit-M#27]
1. The "OK" and "Cancel" label isn't visible in dialogs for my Samsung phone (the example is captured in the screenshot below.)
![Screenshot_20240819_220238_AntiSplit M.png](https://github.com/user-attachments/assets/bb3d5291-2393-429e-b5c7-70629977783b)

2. Some strings localisation aren't applied for some reason (in this case, it's "Fix for ReVanced" and "Fixing for ReVanced…")

**Comment by AbdurazaaqMohammed** [comment]
> The "OK" and "Cancel" label isn't visible in dialogs for my Samsung phone

It should be visible now, I set the text color of the buttons now

> Some strings localisation aren't applied for some reason (in this case, it's "Fix for ReVanced" and "Fixing for ReVanced…")

Those strings were not translated in most languages yet

**Comment by teddysulaimanGL** [comment]
> > Some strings localisation aren't applied for some reason (in this case, it's "Fix for ReVanced" and "Fixing for ReVanced…")
> 
> Those strings were not translated in most languages yet

They are for mine, and I'm pretty sure Italian strings are, too

**Comment by teddysulaimanGL** [comment]
Um, but why is the "Automatically select splits for your device specifications" used twice? The next one should be "Check for updates automatically"

**Comment by AbdurazaaqMohammed** [comment]
Yeah I just messed up the strings, I fixed it now
