### ISSUE TITLE
1.6.2 not working for X app to be patched with ReVanced

### ISSUE THREAD

**Issue by Fredhoob** [AbdurazaaqMohammed/AntiSplit-M#3]
I tried to use the built-in function to make it ready for ReVanced. But the app patched in ReVanced crashes on startup and Android says the app is bugged.

**Comment by Fredhoob** [comment]
But then you still have to sign it with another app, no?

**Comment by Fredhoob** [comment]
It's one and the same option.

**Comment by Fredhoob** [comment]
Which splits do you select after that? All of them? Do you patch the app with ReVanced after that or do you use it like that? Thanks for your help!

**Comment by AbdurazaaqMohammed** [comment]
> > But "select for your device specifications" IS the one with (enable this if you want to use the merged APK in ReVanced Manager).
> 
> I know. Although they're being the same, the culprit seems to be this option and turning it off solved the problem. ![IMG_20240726_204138.jpg](https://private-user-images.githubusercontent.com/71558811/352618462-c4839021-8235-4fa5-b65c-6fc296f3eeb5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMjA5OTYsIm5iZiI6MTcyMjAyMDY5NiwicGF0aCI6Ii83MTU1ODgxMS8zNTI2MTg0NjItYzQ4MzkwMjEtODIzNS00ZmE1LWI2NWMtNmZjMjk2ZjNlZWI1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDE5MDQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1YWFjMTMwZTkwNTJjMWYyM2EwZmFhYjY2MzVjMjQ1YjlmMzJlNWQyYWYyZGEwZTg0YmZmNGUzMmY1NWVjOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OKjBoeiw3p75D4wPNUWOu__id0atTMT8cfWw6qtWrso)
> 
> So turn it off and select "select for your device specifications" in the selection dialog.

This option seems to work for most people but for some it doesn't and I don't know why. Anyway, I  figured the cause of the error. Basically ReVanced Manager is using a library to sign APKs which is performing some types of ZIP validation which it (the library) should not.

https://github.com/ReVanced/revanced-manager/issues/2083#issuecomment-2253313362

**Comment by Fredhoob** [comment]
@AbdurazaaqMohammed So this will be fixed in the next release? Thanks for your quick reaction!
