### ISSUE TITLE
doesn't support .xapk files

### ISSUE THREAD

**Issue by TheCreeperyXYZ** [AbdurazaaqMohammed/AntiSplit-M#33]
Bundled apks that have the .apkm extension work fine, but sometimes files are branded with .xapk, which this app doesn't support.

**Comment by AbdurazaaqMohammed** [comment]
It is supposed to support them... do you get error log (Please send it here)? or the app doesn't let you select them?

**Comment by TheCreeperyXYZ** [comment]
the app doesn't let me select them

**Comment by AbdurazaaqMohammed** [comment]
Can you try sharing the XAPK file from file manager/anywhere and check if you see the option for AntiSplit M
![WhatsApp Image 2024-08-21 at 12 14 28_42defcde](https://github.com/user-attachments/assets/135a1db7-e8cf-40bf-9cc8-9bb6bf74e0d1)

**Comment by TheCreeperyXYZ** [comment]
this worked, thanks 🙏

**Comment by AbdurazaaqMohammed** [comment]
I think this is a problem with the file picker itself becuase I used the same MIME types (to identify files that can be opened) for the intent filter (to show in the share menu) as I did for the file picker.
