### ISSUE TITLE
Some strings don't change language

### ISSUE THREAD

**Issue by Kuddus73** [AbdurazaaqMohammed/AntiSplit-M#38]
There are some strings like `Settings` or `Close` that only follow the system language and they don't change when language is changed.

https://github.com/user-attachments/assets/aece6e32-adea-4214-b0a7-158645203cdd

**Comment by AbdurazaaqMohammed** [comment]
They are new strings I added after the people who contributed those translations did so

**Comment by Kuddus73** [comment]
> They are new strings I added

It's not because they are new strings that haven't been translated yet.
I changed the system language to Italian and see, those strings now remain as Italian and don't change:

https://github.com/user-attachments/assets/d40cdf66-c7f4-46b1-b74a-175a92ea1ad7

**Comment by Kuddus73** [comment]
> They are new strings I added

@AbdurazaaqMohammed it's not happening because they are new strings that haven't been translated yet.
I changed the system language (phone language) to Italian and now those strings remain as Italian and don't change to other languages:

https://github.com/user-attachments/assets/c991d3f8-9e33-4aeb-b890-5eff7a1c1f4c

**Comment by 0xrxL** [comment]
> > They are new strings I added
> 
> @AbdurazaaqMohammed it's not happening because they are new strings that haven't been translated yet. I changed the system language (phone language) to Italian and now those strings remain as Italian and don't change to other languages:
> 
>  Screen_Recording_20240821_112707_AntiSplit.M.mp4

```close``` string was added by @AbdurazaaqMohammed later, due to his forgetfulness.

Anyway more strings has been added in the last 2 days, so take a look to [values/strings.xml](https://github.com/AbdurazaaqMohammed/AntiSplit-M/commits/master/app/src/main/res/values/strings.xml) when you can...and after the implementation of new changes.

**Comment by Kuddus73** [comment]
> `close` string was added by @AbdurazaaqMohammed l> Anyway more strings has been added in the last 2 days, so take a look to [values/strings.xml](https://github.com/AbdurazaaqMohammed/AntiSplit-M/commits/master/app/src/main/res/values/strings.xml) when you can...and after the implementation of new changes.

I don't understand what your comment has to do with the bug reported.

All I'm saying is that there are some strings that only follow the phone's language.
**They don't change by changing the app's language using the `Language` button, those strings only change by changing the phone's language.**

**Comment by Kuddus73** [comment]
> `close` string was added by @AbdurazaaqMohammed later, due to his forgetfulness.
>
> Anyway more strings has been added in the last 2 days, so take a look to [values/strings.xml](https://github.com/AbdurazaaqMohammed/AntiSplit-M/commits/master/app/src/main/res/values/strings.xml) when you can...and after the implementation of new changes.

@0xrxL I don't understand what your comment has to do with the bug reported.

All I'm saying is that there are some strings that only follow the phone's language.
**They don't change by changing the app's language using the `Language` button, those strings only change by changing the phone's language.**

**Comment by 0xrxL** [comment]
Anyway...I noticed that languages like Spanish on this repo, don't have a translation related to ```Close``` button. So it must be added.

**Comment by Kuddus73** [comment]
> But weirdly `Settings` string correctly fallback into it, if you return to homepage and open settings page again.

Not really, if you notice closely, what you wrote only applies to the `Settings` string of the **title** in the left top corner when you open the settings.
The string of the `Settings` **button** below the `Select split APK...` button always follow the system language and it's unchangeable through the `Language` button.

> some strings (only two for the moment: Settings and Close) don't fallback into English, when the traslation is missing.

Also, that's not what I meant because you already added the translations for those 2 strings in Italian so they aren't missing anymore, and yet those 2 strings don't change using the `Language` button.
**What I meant is that some strings don't change their language using the `Language` button, but they change only by changing the system language, because they only follow the system language.**

**Comment by AbdurazaaqMohammed** [comment]
Sorry, every time I add new string, I have to add the code for the language picker to update that string, I forgot to do it for those two, now I did it
