### ISSUE TITLE
The chosen language doesn't get ticked

### ISSUE THREAD

**Issue by Kuddus73** [AbdurazaaqMohammed/AntiSplit-M#40]
The chosen language's tick box appears empty instead of appearing ticked like ☑️.

https://github.com/user-attachments/assets/435e63a8-b06e-4e4e-8446-2f10f790cf2b

**Comment by AbdurazaaqMohammed** [comment]
I don't know why but I could not get it to tick I just removed the checkboxes from the language picker instead

**Comment by Kuddus73** [comment]
> I don't know why but I could not get it to tick I just removed the checkboxes from the language picker instead

@AbdurazaaqMohammed to inform the user about the current language, have you tried making the chosen language **bold**?

**Comment by AbdurazaaqMohammed** [comment]
Now I have done it
