### ISSUE TITLE
Add an animation during splits merging

### ISSUE THREAD

**Issue by 0xrxL** [AbdurazaaqMohammed/AntiSplit-M#45]
With some splits the app works slowly, and this might suggest that app got stuck (more than one time I closed the app before the merging end, and this generated a 0 byte apk). An animation (or whatever) would be needed to prevent misunderstandings.

**Comment by AbdurazaaqMohammed** [comment]
Added in [latest release](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/latest)

**Comment by 0xrxL** [comment]
Thanks
