### ISSUE TITLE
Few design improvements

### ISSUE THREAD

**Issue by 0xrxL** [AbdurazaaqMohammed/AntiSplit-M#50]
To make a more consistent design:

- Make notifications bar transparent (equal to background color).
- Remove edges on settings page (but keep them on warning popups)
![Screenshot_20240825_013053_AntiSplit M](https://github.com/user-attachments/assets/d6e39af0-ea4c-40bd-b9be-8aebfb8837f1)

**Comment by AbdurazaaqMohammed** [comment]
> Make notifications bar transparent (equal to background color).

Added in [latest release](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/latest)

> Remove edges on settings page (but keep them on warning popups)

I think on some devices, it will display between the main screen buttons and will be hard to distinguish between them
