### ISSUE TITLE
Send notification when there's a new update

### ISSUE THREAD

**Issue by Kuddus73** [AbdurazaaqMohammed/AntiSplit-M#62]

**Comment by Hiaashuu** [comment]
Yes please add an option to show update if there's any.

**Comment by AbdurazaaqMohammed** [comment]
I don't know how to do it and I think for most users it will be a waste of battery life and an annoyance.

**Comment by Kuddus73** [comment]
> and I think for most users it will be a waste of battery life and an annoyance.

@AbdurazaaqMohammed like in all apps, the feature will need to be enabled/disabled by user choice.

> I don't know how to do it

Maybe in the future you will able to implement it, so I think would be better to keep this open.
Also, it will prevent opening duplicate requests.

**Comment by Kuddus73** [comment]
> and I think for most users it will be a waste of battery life and an annoyance.

@AbdurazaaqMohammed like in all apps, the feature will need to be enabled/disabled by user choice.

> I don't know how to do it

Maybe in the future you will able to implement it.
So I think it would be better to keep this open, as it will also prevent opening this same request again by others.
