### ISSUE TITLE
Move the settings icon a bit higher

### ISSUE THREAD

**Issue by KN592** [AbdurazaaqMohammed/AntiSplit-M#65]
The phone's control buttons, home button etc are covering most of the settings icon

![Screenshot_20240911-163544_AntiSplit M](https://github.com/user-attachments/assets/3f5ae3fe-5e13-456b-a2cb-83d97dbabbbb)

**Comment by AbdurazaaqMohammed** [comment]
It should be fixed now, I updated the [last release](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/latest)

![WhatsApp Image 2024-09-11 at 09 21 02_fc63f2a3](https://github.com/user-attachments/assets/3b343657-3054-4925-858d-1fe36b52ef8a)
