### ISSUE TITLE
Bug list with Material You design update

### ISSUE THREAD

**Issue by Kuddus73** [AbdurazaaqMohammed/AntiSplit-M#66]
1. Logs are **not fully visible** because of missing padding, currently is not possible to see where the merged file will be saved
![__20240911_211929](https://github.com/user-attachments/assets/638d2b60-272e-4a52-8237-7480fca6ff19)
-
2. `Cancel` button is **missing**
![__20240911_212147](https://github.com/user-attachments/assets/a71968b0-c0aa-49a9-846c-0e5e925eaf2c)
-
3. `Copy logs` button is **missing**
![__20240911_212147](https://github.com/user-attachments/assets/a71968b0-c0aa-49a9-846c-0e5e925eaf2c)
-
4. `Install` button **overlaps** with `Settings` button
![__20240911_215447](https://github.com/user-attachments/assets/118771a1-a549-4bee-9a70-82c4580e165c)
-
5. `Install` button remains visible after selecting a new bundle, during processing the button should disappear and reappear only after saving the new merged file

https://github.com/user-attachments/assets/4cd9b104-510d-41bc-9e94-f19af8ed8b1b

**Comment by AbdurazaaqMohammed** [comment]
Fixed all in [latest release](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/latest)
