### ISSUE TITLE
`Create GitHub Issue` button doesn't do anything

### ISSUE THREAD

**Issue by Kuddus73** [AbdurazaaqMohammed/AntiSplit-M#67]
https://github.com/user-attachments/assets/21abe710-0114-402b-8cc9-c5a58f672c88

**Comment by AbdurazaaqMohammed** [comment]
I could not replicate this.

It looks like in this case the error is caused by selecting a regular APK file instead of a split one, and each file inside the APK is checked, skipped and logged, so the log is very long. Maybe on some devices if the log is too long nothing will happen
