### ISSUE TITLE
Theme switcher bugs

### ISSUE THREAD

**Issue by Kuddus73** [AbdurazaaqMohammed/AntiSplit-M#69]
1. The black theme has this app title bug.

https://github.com/user-attachments/assets/40ccd47d-ede2-41c8-a536-2fdc4d5ad4fb

-

2. In the light theme, the colour of the main body of the app is the same colour of the dark theme.
![Screenshot_20240912_011259_AntiSplit M](https://github.com/user-attachments/assets/b037ae5d-d770-4c4b-9229-0d4894b05405)

**Comment by AbdurazaaqMohammed** [comment]
Fixed
