### ISSUE TITLE
Light theme background bug

### ISSUE THREAD

**Issue by Kuddus73** [AbdurazaaqMohammed/AntiSplit-M#70]
In light theme, it looks the boxes' backgrounds have different colour than the main body.
It is really visible at the corners.
![ _20240912_020153](https://github.com/user-attachments/assets/b3f9e688-fe7b-4ae9-8068-237419684900)

**Comment by AbdurazaaqMohammed** [comment]
I see the shadow on the floating buttons looks really bad, I removed it, but the top one looks fine to me, unless I am missing something, it's different because it is a CardView, I think it looks fine to distinguish from the log below

**Comment by Kuddus73** [comment]
> but the top one looks fine to me, unless I am missing something

@AbdurazaaqMohammed it is the same issue of the bottom floating button.
The shadow does not blend with the background color, making it appear the CardView has a different background colour than the main body.
Also, because of the shadow, the shape looks like a pointed rectangle and not rounded.
![ _20240912_022814](https://github.com/user-attachments/assets/ea9ced73-0f68-4333-a55f-7befc196e884)
![ _20240912_022846](https://github.com/user-attachments/assets/efc13c53-6d1b-4399-b0c3-8f353a1268ae)

**Comment by AbdurazaaqMohammed** [comment]
Wow! Your eyesight is very good! Now I have removed it there also
