### ISSUE TITLE
`Select from Installed Apps` bugs

### ISSUE THREAD

**Issue by Kuddus73** [AbdurazaaqMohammed/AntiSplit-M#71]
1. Double search bars bug
2. `Back` button bug

**Comment by Vertuhai** [comment]
> 1. Double search bars bug

In addition to all this, the program does not see all installed applications, not counting system ones.

**Comment by AbdurazaaqMohammed** [comment]
Fixed in [latest release](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/latest)

**Comment by Kuddus73** [comment]
> Fixed in [latest release](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/latest)

@AbdurazaaqMohammed the second bug hasn't been fixed.

**Comment by drogga** [comment]
I don't get why is there a back button at all.

**Comment by AbdurazaaqMohammed** [comment]
It is part of the material search view, anyway I fixed it now, it will close the dialog
