### ISSUE TITLE
Swiping floating button down bug

### ISSUE THREAD

**Issue by Kuddus73** [AbdurazaaqMohammed/AntiSplit-M#73]
The swiping down works only once:

https://github.com/user-attachments/assets/61843e5d-1cae-4d43-bf72-e403ccdeb761

Also, just curiosity, what's this feature needed for?

**Comment by AbdurazaaqMohammed** [comment]
@drogga [wanted it](https://github.com/AbdurazaaqMohammed/AntiSplit-M/issues/63#issuecomment-2345490306), maybe I will just make the buttons translucent instead

**Comment by Vertuhai** [comment]
> Also, just curiosity, what's this feature needed for?

This function does not carry any functional settings.
Therefore, you should not focus your attention on such a trifle that is barely noticeable.
