### ISSUE TITLE
Read only filesystem bug

### ISSUE THREAD

**Issue by Auditore64** [AbdurazaaqMohammed/AntiSplit-M#76]
- ROM: Lineageos 21
- Android version: 14
- Device: Poco X3 NFC
- Root: Magisk

 I was trying to merge the twitter apk from ApkMirror and this bug always occurs (I tested with other apks besides twitter too). I can't say what could be the cause of this bug, if it is relevant I use the following modules in magisk: LSPosed fork from Jing Matrix, QuickSwitch and Play Integrity Fix

java.nio.file.FileSystemException: com.twitter.android_10.58.0-release.0-310580000_4arch_7dpi_23lang_4a0563c01f0435667a1b9e1520974bb4_apkmirror.com.apkm: Read-only file systemsun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:220)java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)java.nio.file.Files.newOutputStream(Files.java:216)E.c.i(SourceFile:1)com.starry.FileUtils.getOutputStream(SourceFile:2)com.starry.FileUtils.copyFile(SourceFile:5)com.reandroid.apkeditor.merge.Merger.extractAndLoad(SourceFile:288)com.reandroid.apkeditor.merge.Merger.run(SourceFile:56)com.abdurazaaqmohammed.AntiSplit.main.MainActivity$ProcessTask.doInBackground(SourceFile:41)com.abdurazaaqmohammed.AntiSplit.main.MainActivity$ProcessTask.doInBackground(SourceFile:1)android.os.AsyncTask$3.call(AsyncTask.java:394)java.util.concurrent.FutureTask.run(FutureTask.java:264)android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)java.lang.Thread.run(Thread.java:1012)Searching apk files…/document/primary:Download/com.twitter.android_10.58.0-release.0-310580000_4arch_7dpi_23lang_4a0563c01f0435667a1b9e1520974bb4_apkmirror.com.apkmSkipping META-INF/MANIFEST.MF: Not an APK fileSkipping META-INF/APKMIRRO.SF: Not an APK fileSkipping META-INF/APKMIRRO.RSA: Not an APK fileSkipping info.json: Not an APK fileSkipping icon.png: Not an APK file

**Comment by AbdurazaaqMohammed** [comment]
I tried to fix it, please check the [latest release](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/latest)

**Comment by drogga** [comment]
What is is with the log, so it doesn't have line breaks, aren't they used in the app or what, because GH works with all of them, so it shouldn't matter here...

Windows = (CRLF) ¦ (\r\n)
Unix-like {Linux/Android} = (LF) ¦ (/n)
MacOS = (CR) ¦ (\r)

**Comment by Auditore64** [comment]
> I tried to fix it, please check the [latest release](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/latest)

I tested it and the app shows the same problem. Here is the log that the app showed

java.io.FileNotFoundException: com.twitter.android_10.58.0-release.0-310580000_4arch_7dpi_23lang_4a0563c01f0435667a1b9e1520974bb4_apkmirror.com.apkm: open failed: EROFS (Read-only file system)
libcore.io.IoBridge.open(IoBridge.java:574)
java.io.FileOutputStream.<init>(FileOutputStream.java:259)
java.io.FileOutputStream.<init>(FileOutputStream.java:208)
com.starry.StupidOS.getOutputStream(SourceFile:30)
com.starry.FileUtils.getOutputStream(SourceFile:2)
com.starry.FileUtils.copyFile(SourceFile:5)
com.reandroid.apkeditor.merge.Merger.extractAndLoad(SourceFile:288)
com.reandroid.apkeditor.merge.Merger.run(SourceFile:56)
com.abdurazaaqmohammed.AntiSplit.main.MainActivity$ProcessTask.doInBackground(SourceFile:41)
com.abdurazaaqmohammed.AntiSplit.main.MainActivity$ProcessTask.doInBackground(SourceFile:1)
android.os.AsyncTask$3.call(AsyncTask.java:394)
java.util.concurrent.FutureTask.run(FutureTask.java:264)
android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
java.lang.Thread.run(Thread.java:1012)

Searching apk files…
/document/primary:Download/com.twitter.android_10.58.0-release.0-310580000_4arch_7dpi_23lang_4a0563c01f0435667a1b9e1520974bb4_apkmirror.com.apkm
Skipping META-INF/MANIFEST.MF: Not an APK file
Skipping META-INF/APKMIRRO.SF: Not an APK file
Skipping META-INF/APKMIRRO.RSA: Not an APK file
Skipping info.json: Not an APK file
Skipping icon.png: Not an APK file

**Comment by AbdurazaaqMohammed** [comment]
I try to fix it again, please check the [latest release](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/latest)

**Comment by drogga** [comment]
What is it with the error logs (not file operation ones), so it doesn't have line breaks, aren't they used in the app or what ?, because GH works with all of them, so it shouldn't matter here and it shouldn't be such a basically unreadable mess...
I don't believe is an encoding problem.

Windows = (CRLF) ¦ (\r\n)
Unix-like {Linux/Android} = (LF) ¦ (\n)
MacOS = (CR) ¦ (\r)

**Comment by Auditore64** [comment]
> I try to fix it again, please check the [latest release](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/latest)

Same thing, so far I've tried clearing all application data, uninstalling the application and installing the latest version, and using the Permission Manager X app to give all possible permissions to AntiSplit but it still didn't work.

Here's a screenshot of Permission Manager X in case it helps

![Screenshot_20240913-110304_Permission Manager X](https://github.com/user-attachments/assets/f219a516-f3d4-45ca-840d-cf94c7d1fa9a)

AntiSplit Log:

java.io.FileNotFoundException: com.twitter.android.apk: open failed: EROFS (Read-only file system)
libcore.io.IoBridge.open(IoBridge.java:574)
java.io.FileOutputStream.<init>(FileOutputStream.java:259)
java.io.FileOutputStream.<init>(FileOutputStream.java:208)
com.starry.StupidOS.getOutputStream(SourceFile:30)
com.starry.FileUtils.getOutputStream(SourceFile:2)
com.reandroid.apkeditor.merge.Merger.extractZipFile(SourceFile:80)
com.reandroid.apkeditor.merge.Merger.extractAndLoad(SourceFile:329)
com.reandroid.apkeditor.merge.Merger.run(SourceFile:56)
com.abdurazaaqmohammed.AntiSplit.main.MainActivity$ProcessTask.doInBackground(SourceFile:41)
com.abdurazaaqmohammed.AntiSplit.main.MainActivity$ProcessTask.doInBackground(SourceFile:1)
android.os.AsyncTask$3.call(AsyncTask.java:394)
java.util.concurrent.FutureTask.run(FutureTask.java:264)
android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
java.lang.Thread.run(Thread.java:1012)

Searching apk files…
/document/primary:Download/X_10.58.0-release.0_APKPure.xapk

**Comment by AbdurazaaqMohammed** [comment]
Can you please try this older version and see if works https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/download/1.6.6.2/AntiSplit-M.v1.6.6.2.apk

I am trying to figure out if this is caused by a change I made recently

**Comment by Auditore64** [comment]
> Can you please try this older version and see if works https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/download/1.6.6.2/AntiSplit-M.v1.6.6.2.apk
> 
> I am trying to figure out if this is caused by a change I made recently

I tested it and it shows the same error 😕

Log:

java.nio.file.FileSystemException: com.twitter.android.apk: Read-only file system
sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:220)
java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
java.nio.file.Files.newOutputStream(Files.java:216)
f.a.e(SourceFile:1)
com.starry.FileUtils.getOutputStream(SourceFile:3)
com.reandroid.apkeditor.merge.Merger.extractZipFile(SourceFile:86)
com.reandroid.apkeditor.merge.Merger.extractAndLoad(SourceFile:385)
com.reandroid.apkeditor.merge.Merger.run(SourceFile:56)
com.abdurazaaqmohammed.AntiSplit.main.MainActivity$ProcessTask.doInBackground(SourceFile:41)
com.abdurazaaqmohammed.AntiSplit.main.MainActivity$ProcessTask.doInBackground(SourceFile:1)
android.os.AsyncTask$3.call(AsyncTask.java:394)
java.util.concurrent.FutureTask.run(FutureTask.java:264)
android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
java.lang.Thread.run(Thread.java:1012)

Searching apk files…
/document/primary:Download/X_10.58.0-release.0_APKPure.xapk

**Comment by AbdurazaaqMohammed** [comment]
It looks like it is failing to write to external cache dir somehow. Can you test this, I just change it to use the internal cache dir
https://files.catbox.moe/d02apu.apk

**Comment by Auditore64** [comment]
> It looks like it is failing to write to external cache dir somehow. Can you test this, I just change it to use the internal cache dir https://files.catbox.moe/d02apu.apk

Worked like a charm, thank you bro🤝

![Screenshot_20240913-132316_AntiSplit M](https://github.com/user-attachments/assets/e8be8935-7b30-422d-9d62-5b5f372ab771)
