### ISSUE TITLE
Light theme navigation bar's icons are invisible

### ISSUE THREAD

**Issue by Kuddus73** [AbdurazaaqMohammed/AntiSplit-M#81]
With the recent changes, the icons of the navigation bar in light theme look invisible.

![Screenshot_20240913_161430_AntiSplit M](https://github.com/user-attachments/assets/faef48ec-160f-44a0-a47b-ca3fd99f280a)
Zoomed in:
![20240913_161744](https://github.com/user-attachments/assets/4291d331-3d10-4086-a51e-0a19dd58fee5)

Only the light theme has this bug, other themes are fine.

You could follow Twitter's themes examples:
**Light**
![Screenshot_20240913_163133_X](https://github.com/user-attachments/assets/5da200f8-5842-4bd2-89e8-cc87aeead516)
**Dark**
![Screenshot_20240913_163138_X](https://github.com/user-attachments/assets/0baea589-04c0-4544-8787-d458e7fe9a28)
**Black**
![Screenshot_20240913_163143_X](https://github.com/user-attachments/assets/88e3f245-7bb2-4f92-a696-c5536a618b0d)

**Comment by AbdurazaaqMohammed** [comment]
I test this fixed in official Samsung emulator

![image](https://github.com/user-attachments/assets/87ceed12-d082-4aba-8fcc-bc414a0ba47c)
