### ISSUE TITLE
Sort splits alphabetically

### ISSUE THREAD

**Issue by Dimon184** [AbdurazaaqMohammed/AntiSplit-M#82]
Sorting now looks like this:
![Sort1](https://github.com/user-attachments/assets/ec6b4fc5-b532-4fea-9cd2-d7a8f22eb64b)

It is difficult to find and choose the right splits.

Thnx

**Comment by AbdurazaaqMohammed** [comment]
Done in [latest release](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/latest)
