### ISSUE TITLE
Make the status bar the same colour as the main body in all themes

### ISSUE THREAD

**Issue by Kuddus73** [AbdurazaaqMohammed/AntiSplit-M#83]
**Light:**
![__20240913_175118](https://github.com/user-attachments/assets/5350c44e-54b3-4b16-925b-b7669229eee9)

**Dark:**
![__20240913_175152](https://github.com/user-attachments/assets/7a537d71-f23f-41dc-89b0-bd0c312d488f)

**Comment by AbdurazaaqMohammed** [comment]
I test this fixed in official Samsung emulator

![image](https://github.com/user-attachments/assets/87ceed12-d082-4aba-8fcc-bc414a0ba47c)
