### ISSUE TITLE
Remove shadow from theme selector box

### ISSUE THREAD

**Issue by Kuddus73** [AbdurazaaqMohammed/AntiSplit-M#85]
![Screenshot_20240914_033351_AntiSplit M](https://github.com/user-attachments/assets/dc7197b1-2550-4822-ba08-dca73b513725)
The reason is explained [here](https://github.com/AbdurazaaqMohammed/AntiSplit-M/issues/70#issuecomment-2345089005).

**Comment by AbdurazaaqMohammed** [comment]
Done, I update the last release because the changes are minor
