### ISSUE TITLE
Add space to the left of search bar

### ISSUE THREAD

**Issue by Kuddus73** [AbdurazaaqMohammed/AntiSplit-M#86]
![ _20240914_033916](https://github.com/user-attachments/assets/a1f4d423-ee62-40f6-b0a2-b0d8cc103910)

**Comment by AbdurazaaqMohammed** [comment]
Done, I update the last release because the changes are minor
![WhatsApp Image 2024-09-14 at 12 23 56_c436ecec](https://github.com/user-attachments/assets/7a8a5843-3c7a-4769-9670-59cfd2aa270d)
