### ISSUE TITLE
Add space to the top of magnifying glass

### ISSUE THREAD

**Issue by Kuddus73** [AbdurazaaqMohammed/AntiSplit-M#87]
![ _20240914_181917](https://github.com/user-attachments/assets/170132b2-dfaf-49d0-be7a-5a580d4452e3)

**Comment by 0xrxL** [comment]
@AbdurazaaqMohammed A new magnifier icon for you (it more reflect the minimal app style):

![search_magnifier_icon_145939](https://github.com/user-attachments/assets/ff53a384-3359-4194-a7a2-91f0b2d1e488)
![20240915_013802](https://github.com/user-attachments/assets/3448f163-64e7-4b04-a5dc-94efe5b534c8)

**Comment by AbdurazaaqMohammed** [comment]
Done in [latest release](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/latest)
![WhatsApp Image 2024-09-15 at 07 18 36_b23aa2a2](https://github.com/user-attachments/assets/82cb0e2a-77a7-4b85-a2d2-83e5dca365f9)
