### ISSUE TITLE
Update page improvements

### ISSUE THREAD

**Issue by Kuddus73** [AbdurazaaqMohammed/AntiSplit-M#89]
1. Centre the title
![ _20240915_044032](https://github.com/user-attachments/assets/f56512fc-1cfa-4466-a46b-e86a731d2037)
-
2. After the update version put a new line to differentiate from changelogs
![ _20240915_044136](https://github.com/user-attachments/assets/265ba566-50a7-4787-b384-da56724f8073)
-
3. Add space to the left
![ _20240915_044246](https://github.com/user-attachments/assets/4284b969-bbcd-472d-a62d-90203ef33230)
-
4. Make `Cancel` button the 3rd button
![ _20240915_044343](https://github.com/user-attachments/assets/207d7f43-0d55-4026-a93f-c9c65a6b5550)

**Comment by AbdurazaaqMohammed** [comment]
Done in [latest release](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/latest)
![WhatsApp Image 2024-09-15 at 07 19 28_f4fec47b](https://github.com/user-attachments/assets/539e6646-5ecb-4ec0-8f29-bba92aa9a832)

**Comment by Kuddus73** [comment]
@AbdurazaaqMohammed wouldn't be possible to centre only the title `Update available` and leaving the rest aligned to the left?

**Comment by Kuddus73** [comment]
> 1. Centre the title

@AbdurazaaqMohammed wouldn't be possible to centre **only the title** `Update available` and leaving the rest aligned to the left?

**Comment by AbdurazaaqMohammed** [comment]
Done, I update the last release
