### ISSUE TITLE
Error page improvements

### ISSUE THREAD

**Issue by Kuddus73** [AbdurazaaqMohammed/AntiSplit-M#90]
![ _20240915_045457](https://github.com/user-attachments/assets/5dffcc77-5054-48d9-bd29-bc4f20cd4eb1)
1. Give similar spacing between the buttons icons
2. Align the icons to the right
3. Move the icons at the bottom
4. Change the order of the icons to `Copy logs`, `Open GitHub issue` and `Close`

**Comment by AbdurazaaqMohammed** [comment]
![WhatsApp Image 2024-09-15 at 08 25 33_250df0b4](https://github.com/user-attachments/assets/1cb72f3e-3127-496e-966d-4c41251c26d8)
