### ISSUE TITLE
Error page scrolling bug

### ISSUE THREAD

**Issue by Kuddus73** [AbdurazaaqMohammed/AntiSplit-M#91]
The scrolling on the error page doesn't work properly.

https://github.com/user-attachments/assets/ecba7f48-93ab-4b2f-ac20-376ac9d47980

**Comment by AbdurazaaqMohammed** [comment]
Fixed in [latest release](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/latest)

![WhatsApp Image 2024-09-15 at 07 40 45_f7e0cc06](https://github.com/user-attachments/assets/f7e01688-968a-4767-9f39-caa824b3c8f9)
