### ISSUE TITLE
Add option to edit the suffix of the processed file

### ISSUE THREAD

**Issue by Kuddus73** [AbdurazaaqMohammed/AntiSplit-M#96]
Currently, the processed file has automatically the word `antisplit` added to its name.

1. Add option to edit the suffix
2. Add also an option to not add anything to the processed file

**Comment by AbdurazaaqMohammed** [comment]
I added option to edit the suffix, it can be blank 

![WhatsApp Image 2024-09-29 at 02 01 33_ec29cd1b](https://github.com/user-attachments/assets/02bdb32a-4420-4cc0-afcb-0bae8cecb2fc)
