### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by JustGanon** [AbdurazaaqMohammed/AntiSplit-M#97]
java.io.IOException: Error on ZipFile /data/user/0/com.abdurazaaqmohammed.AntiSplit/cache/TikTok_36.5.5_APKPure (1)_antisplit.apkorg.apache.commons.compress.archivers.zip.ZipFile.<init>(SourceFile:39)org.apache.commons.compress.archivers.zip.ZipFile.<init>(SourceFile:12)org.apache.commons.compress.archivers.zip.ZipFile.<init>(SourceFile:9)org.apache.commons.compress.archivers.zip.ZipFile.<init>(SourceFile:2)org.apache.commons.compress.archivers.zip.ZipFile.<init>(SourceFile:1)com.reandroid.apkeditor.merge.Merger.extractAndLoad(SourceFile:317)com.reandroid.apkeditor.merge.Merger.run(SourceFile:57)com.abdurazaaqmohammed.AntiSplit.main.MainActivity$ProcessTask.doInBackground(SourceFile:41)com.abdurazaaqmohammed.AntiSplit.main.MainActivity$ProcessTask.doInBackground(SourceFile:1)android.os.AsyncTask$3.call(AsyncTask.java:394)java.util.concurrent.FutureTask.run(FutureTask.java:264)android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)java.lang.Thread.run(Thread.java:1012)Searching apk files…/document/primary:Aliucord/TikTok_36.5.5_APKPure (1)_antisplit.apk

**Comment by AbdurazaaqMohammed** [comment]
> TikTok_36.5.5_APKPure (1)_antisplit.apk

You are trying to merge an APK that is already merged
