### ISSUE TITLE
Don't overwrite file via `Select split APK to Merge/AntiSplit`

### ISSUE THREAD

**Issue by Kuddus73** [AbdurazaaqMohammed/AntiSplit-M#99]
Currently via `Select split APK to Merge/AntiSplit` the file gets overwritten and replaced with the new file if it has the same name of an existing file:

https://github.com/user-attachments/assets/2acbedfc-1555-4071-a3f2-854a3c02d5d3

And via `Select from Installed Apps` the overwriting doesn't happen even with the same file name because it automatically adds _space_ (1) or _space_ (2) and so on at the end of the file name of the new file:

https://github.com/user-attachments/assets/f61af6ec-9cf6-44bc-87a1-e3152be7954e

Would it be possible to **not overwrite** files even via `Select split APK to Merge/AntiSplit`?

**Comment by AbdurazaaqMohammed** [comment]
In the [latest release](https://github.com/AbdurazaaqMohammed/AntiSplit-M/releases/latest) it should rename file if it already exists.

> The document provider [SAF - the Save prompt] also thinks that the file is 0 bytes, which can be seen in the 2nd video and IDK why it doesn't properly trigger or at all the MediaScanner or whatever there might be wrong/the issue.

It happens for me only when inside "Downloads" in the sidebar (It happens with other apps too), all other folders displays fine
